### ISSUE TITLE
Repodata is over 2 weeks old Random message

### ISSUE THREAD

**Issue by michaelhidalgo** [k8-proxy/s-k8-core-images#3]
Running container randomly shows up this error "Repodata is over 2 weeks old. Install yum-cron? Or run: yum makecache fast"

<img width="1012" alt="Screen Shot 2020-11-16 at 19 31 56" src="https://user-images.githubusercontent.com/1732035/99328865-97859a00-2842-11eb-8a03-cadf48a1ec1f.png">

Which could cause some issues later. It seems like the solution to prevent this issue from happening is by running  this command **yum clean all**

**Comment by michaelhidalgo** [comment]
Actually, the issue is that the image pushed into the docker hub is older (more than 2 weeks) so we need to make sure it is updated frequently.

**Comment by michaelhidalgo** [comment]
@zaddy6 can we push into docker hub a new version please?

**Comment by dtollaku** [comment]
@michaelhidalgo anything to do here or can we close this issue?

**Comment by michaelhidalgo** [comment]
I think we can close this one @dtollaku , thanks for checking,
